### ISSUE TITLE
Doctype! legacy-compat not honored

### ISSUE THREAD

**Issue by dnguyenchevy** [flavorjones/loofah#110]
It appears that Loofah doesn't keep/honor "about:legacy-compat "

``` ruby
doc_str = "<!DOCTYPE html SYSTEM \"about:legacy-compat\"><html></html>"

Loofah.document(doc_str).to_html
#=> "<!DOCTYPE html>\n<html></html>\n"
```

Is there a reason this was dropped? 

I was expecting it to keep the same DOCTYPE.

**Comment by flavorjones** [comment]
Hi, thanks for asking this question. And apologies for the long delay in replying.

This appears to be behavior of Nokogiri, and not loofah:

```ruby
require 'nokogiri'

doc_str = "<!DOCTYPE html SYSTEM \"about:legacy-compat\"><html></html>"

puts Nokogiri::HTML(doc_str).to_html
# => <!DOCTYPE html>
#    <html></html>
```

This is likely because this is an HTML5 addition, and Nokogiri's libxml2 parser only supports HTML4. You may want to inquire with the `nokogumbo` project how they recommend proceeding for HTML5 sanitization.

Sorry I can't be of more help right now.
