### ISSUE TITLE
Some new css attributes are not referenced in the list and end up being removed from the sanitized string. like align-items.

### ISSUE THREAD

**Issue by miguelperez** [flavorjones/loofah#197]
Flex properties like align-items are removed from the sanitized css.

https://github.com/flavorjones/loofah/blob/3e28e62fc3ec47d8fba7a28f56418374af265166/lib/loofah/html5/safelist.rb#L550

Is there a particular reason security those are not included? or Should I add a PR with the missing attributes? @flavorjones 

UPDATE: 
for reference, this is a complete list of CSS Properties: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

**Comment by flavorjones** [comment]
Hi @miguelperez yes, please submit a PR with any additional CSS properties that you think should be included. This list was snapshot in 2008 in commit c673657 taken from http://code.google.com/p/html5lib/ and we've been adding more properties as the spec has evolved and as people needed it.

There is some half-finished work to port Loofah to use [DOMPurify](https://github.com/cure53/DOMPurify) and its CSS properties safelist -- see https://github.com/flavorjones/loofah/issues/155. Rather than generating and keeping our own list, the end game is to use DOMPurify's list, because it's widely-used and well-maintained.

Hope this helps!

**Comment by flavorjones** [comment]
Fixed in https://github.com/flavorjones/loofah/releases/tag/v2.8.0
