### ISSUE TITLE
Can Loofah support <style> element?

### ISSUE THREAD

**Issue by icem** [flavorjones/loofah#83]
If Loofah accepts inline styles, why it filter <style> elements? 
That will require scrubbing css rules of course.

    <style type="text/css">
        p { color: #ccc }
        #foo { margin: 10px; }
    </style>

**Comment by flavorjones** [comment]
Thanks for asking this question. Loofah has ported the `html5lib` implementation to work with Nokogiri in Ruby. I didn't make a conscious choice to include or exclude the functionality, I just ported it. This is not a sufficient answer for your question, though, so I reflected and did some digging.

Some history on this implementation is available here:

> https://wiki.whatwg.org/wiki/Sanitization_rules

which indicates that perhaps we've all been copy-pasting the same thing for years, without asking these questions.

#lazyweb, is there a reason that `html5lib` and its predecessors sanitize tag `style` attributes, but don't do the same for `style` tags? (I'll be tweeting this question.)

**Comment by brauliobo** [comment]
I've added a set of tag and attributes to Loofah, inside a rails initializer. Some are very basic, like `source` which comes inside `audio`.

```ruby
require 'loofah/helpers'

ActionView::Base.full_sanitizer = Loofah::Helpers::ActionView::FullSanitizer.new
ActionView::Base.white_list_sanitizer = Loofah::Helpers::ActionView::WhiteListSanitizer.new

Loofah::HTML5::WhiteList::ALLOWED_ELEMENTS_WITH_LIBXML2 += %w[ 
  img object embed param table tr th td applet comment iframe audio video source
]

Loofah::HTML5::WhiteList::ALLOWED_ATTRIBUTES += %w[ 
  align border alt vspace hspace width heigth value type data
  style target codebase archive classid code flashvars scrolling frameborder controls autoplay colspan
]
```

**Comment by gsnedders** [comment]
html5lib and the other related sanitisers were basically all written by Mark Pilgrim and Sam Ruby — it's hardly surprising they all allow basically the same set. They've diverged a bit over time, but that's just different things getting different patches and not everything staying in sync.

The problem with the style element is I'm not sure it can safely be done at all. You need to ensure that no rule could affect anything outside of the subtree — and you have no knowledge of what is outwith that subtree. We could only allow scoped style elements, but that's not safe because on Firefox supports them.

**Comment by flavorjones** [comment]
@gsnedders - Thanks for the insightful response.

@icem Does @gsnedders's response help understand this decision at all?

I'm going to go ahead and close this, but feel free to update it if you'd like to continue the conversation.

**Comment by brauliobo** [comment]
@flavorjones I still think some important and basic attributes and elements are missing on the allowed lists
