### ISSUE TITLE
`strip_tags` in Loofah does escape entities, while in Rails it doesn’t

### ISSUE THREAD

**Issue by noniq** [flavorjones/loofah#93]
In the Rails console:

``` ruby
require "loofah/helpers"
Loofah::Helpers.strip_tags('foo"bar') # => "foo&quot;bar"
helper.strip_tags('foo"bar') # => "foo\"bar"
```

Not sure if that is really a bug, but the Readme states that `strip_tags` is meant as drop-in replacement for the Rails ActionView helper of the same name and this is currently not the case.

**Comment by flavorjones** [comment]
Hi @noniq,

Thanks for asking this question. The README was true at the time, but that was before Rails adopted Loofah and decided to *not* escape HTML entities. IMHO, Loofah is doing the right thing here, but Rails is trying to be backwards-compatible and so the situation is a bit muddled, I think.

I'm CCing @rafaelfranca in case he wants to comment.

**Comment by rafaelfranca** [comment]
I'm not sure what is right here. I do agree that using strip tags to be used only in HTML views it doesn't matter if you escape the HTML entities or not but when the same information can be used in HTML views and let say in a text-only email it feel wrong to escape the entities.

So lets say that you are sanitizing the company name and you input `Ruby & Rails` and you send an text email, the users will get `Ruby &amp; Rails` as the company name.

I understand that this is a hard problem to solve (I'm trying to find a good solution for the last 4 weeks) and we may need a way to users tell what they expect.

In my opinion we should match the same behavior in both Loofah and Rails but having a way to not escaping the entities while being safe.

**Comment by milgner** [comment]
Just stumbled upon this thread while trying to debug some issues coming up from upgrading to Rails 5. At one point we use a `Rails::Html::FullSanitizer` to sanitize our input before putting it into the database. With the new behavior it will always escape entities which we would like to prevent as this is something that can be done depending on the output medium. It is, of course, the correct approach if the sanitizer is used in the context of HTML output, but when - for example - outputting to a JSON API or - as you already mentioned - a text-only email, it is not the desired result.

In that regard, it would be great to have an option available to prevent this specific part of sanitation from happening.

**Comment by flavorjones** [comment]
Loofah makes available a wide variety of methods to generate either text or HTML output. Is there a compelling reason why these can't be used?

What I'm saying is, I'm not sure what problem we're trying to solve. Do we want to update the docs to note this behavioral difference? Do we want to update the helper to match Rails's current behavior? Do we want Rails's simplistic assumptions to be busted and allow context-specific generation of either text or HTML?

Nothing in this issue is actionable, yet. Up-thumbing and saying "It would be great to have an option available" doesn't help clarify either the problem or the solution.

@rafaelfranca help me out here. I haven't coded in or on Rails in years and someone with expertise and a plan needs to provide guidance.

**Comment by rafaelfranca** [comment]
Rails is now matching the behavior of loofah again https://github.com/rails/rails-html-sanitizer/blob/master/test/sanitizer_test.rb#L119.

The issue @milgner mentioned is that they use the Rails sanitizers (thus loofah sanitizers) to sanitize the user input. In my opinion sanitizing the input is the problem here. If you sanitize at input time you can't chose how the sanitization will happen. If you sanitize without escaping and you present as HTML you may introduce XSS bugs. If you sanitize with escaping and you present as text the escaping will be already there.

The correct fix it to sanitize on presentation time, that is whey you actually knows how you want to present.

**Comment by flavorjones** [comment]
That's great news. I'm going to close this issue out. @milgner let me know if you have more questions about how to use Loofah to do what you want to do.

**Comment by jduarte** [comment]
@flavorjones @milgner and in this case how to use Loofah to make that?

If we call `Loofah::Helpers.strip_tags('Ruby & Rails')`  we'll still get `Ruby &amp; Rails`

**Comment by flavorjones** [comment]
@jduarte the behavior you're describing is intended behavior. A bare `&` character is not valid HTML, and so emitting HTML will cause this to be entity-escaped as `&amp;`.

**Comment by EugZol** [comment]
> and so emitting HTML will cause this to be entity-escaped

But why is it escaped when emitting text?

```
2.5.1 :002 > Loofah.fragment("Ruby & Rails").text
 => "Ruby &amp; Rails"
2.5.1 :003 > Loofah.fragment("Ruby & Rails").to_text
 => "Ruby &amp; Rails"
```
